<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Company By ICO</title>
</head>

<body class="main">
    <div class="container">
        <div class="col-md-6 mt-5">
            <div>
                <?php if (isset($error)) : ?>
                    <div class="alert alert-danger" role="alert">
                        <?= $error ?>
                    </div>
                <?php endif; ?>
            </div>
            <form action="/company" method="POST">
                <div class="form-group">
                    <label for="ico">Zadej ICO spolecnosti</label>
                    <input type="text" class="form-control form-control-sm" id="ico" placeholder="ICO" name="ico" required>
                    <small id="icoHelp" class="form-text text-muted">musi obsahovat 8 cisel</small>
                </div>
                <button type="submit" class="btn btn-primary mb-2">Confirm</button>
            </form>
            <hr>
        </div>
    </div>
</body>
<div>

</html>